### ISSUE TITLE
IndexError:run demo with 'kitti' model

### ISSUE THREAD

**Issue by tracykim** [XuyangBai/D3Feat#10]
HI, i want to run demo with 'kitti' model, so i change the [path](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/demo_registration.py#L197) to 'results_kitti/Log_11011605/'. Howerver, an error occurred on this [line](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/models/KPFCNN_model.py#L119) 
IndexError: tuple index out of range
I would appreciate it if you could help me.

**Comment by XuyangBai** [comment]
Hi @tracykim The key 'trans' is only for KITTI dataset, and for the demo there is no `trans` for the input list. So you may manually set `config.dataset = ''` after loading the config to avoid this error.

BTW, If you are testing the KITTI model on point cloud of outdoor scenes, then it should work well. But if you use are using the two demo .ply in `demo_data` selected from 3DMatch, you should take care of the voxel size as well as the receptive field because they have different scales with KITTI dataset. Basically you need to 
1. set the `config.first_subsampling_dl` to a proper value (e.g. 0.03 for point cloud from 3DMatch. The origin value for KITTI is 0.30 which is too big for point cloud from 3DMatch)
2. change the scale of the kernel points as I mentioned [here](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/demo_registration.py#L139).
 
Hope that helps.

**Comment by tracykim** [comment]
Hi, thanks for your advice.I will test on my data of outdoor scenes.

**Comment by tracykim** [comment]
Hi @XuyangBai The performance of D3Feat on my data is well, thanks for your work and help.
best.

**Comment by XuyangBai** [comment]
Hi @tracykim Glad to here that!
